# Generated by Django 3.1.1 on 2020-09-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmhunter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_id',
            field=models.BigIntegerField(),
        ),
    ]
