# Generated by Django 3.1.7 on 2021-03-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmhunter', '0002_auto_20200914_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='openid',
            name='user_filled_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
