name: pyinstaller

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -U -r client/requirements.txt
        python3 -m pip install -U pyinstaller
    - name: pyinstaller
      run: |
        cd client && pyinstaller dmhunter-client.py --onefile
    - uses: actions/upload-artifact@v3
      if: success()
      with:
        path: client/dist/
